import { useEmbeddedData } from '../data/EmbeddedDataContext.tsx';
import { fmtBytes } from '../format/bytes.ts';
import { useAssumptions } from '../hooks/useAssumptions.tsx';
import { Citation } from '../primitives/Citation.tsx';

export function MethodologyAppendix() {
  const data = useEmbeddedData();
  const { assumptions } = useAssumptions();
  const org = data.orgOverview;
  const cov = data.dependabotCoverage;

  return (
    <section className="border-foreground text-foreground mt-20 border-t pt-10 text-sm">
      <details>
        <summary className="text-foreground hover:text-muted-foreground cursor-pointer text-base font-semibold tracking-tight select-none">
          How this report was calculated
        </summary>

        <div className="mt-5 space-y-6">
          <div>
            <h3 className="text-foreground font-semibold">Cost math</h3>
            <ul className="text-foreground mt-2 list-disc space-y-1.5 pl-5 leading-relaxed">
              <li>
                Cost in window = merged PRs &times; minutes per PR &divide; 60 &times; hourly rate. Currently:{' '}
                {data.costEstimate.mergedInWindow} PRs &times; {assumptions.minutesPerPr} min &divide; 60 &times; $
                {assumptions.hourlyRateUsd}/hr.
              </li>
              <li>
                Monthly run rate scales the window cost by (365 / 12) / windowDays. Annualized = monthly &times; 12.
              </li>
              <li>
                The 5 min/PR default sits at the low end of Mend's published 15&ndash;60 min/week per developer
                <Citation source="mend-renovate-roi" />. The $150/hr default reflects a $300k fully-loaded engineer cost
                divided by 2,000 working hours.
              </li>
              <li>Savings scenarios multiply the monthly cost by the auto-merge share (50%, 60%, 70%, 80%).</li>
              <li>Bot accounts are excluded from merger and reviewer counts.</li>
            </ul>
          </div>

          <div>
            <h3 className="text-foreground font-semibold">Data window and scope</h3>
            <ul className="text-foreground mt-2 list-disc space-y-1.5 pl-5 leading-relaxed">
              <li>
                Window: {data.meta.windowDays} days ending {data.meta.generatedAt.slice(0, 10)}.
              </li>
              <li>
                Repos scanned: {org.repoCount} active ({org.publicCount} public, {org.privateCount} private,{' '}
                {org.internalCount} internal)
                {org.archivedExcluded > 0 ? `; ${org.archivedExcluded} archived repos excluded` : ''}.
              </li>
              <li>
                Dependabot coverage: {cov.reposWithConfig} repos ({cov.reposWithConfigPercentage}%) have a config;{' '}
                {cov.reposWithSecurityUpdates} ({cov.reposWithSecurityUpdatesPercentage}%) have security updates
                enabled.
              </li>
              <li>{org.activeHumanCommitters} distinct human committers active in window.</li>
            </ul>
          </div>

          {org.topLanguages.length > 0 && (
            <div>
              <h3 className="text-foreground font-semibold">Language mix</h3>
              <ul className="text-foreground mt-2 list-disc space-y-1.5 pl-5 leading-relaxed">
                {org.topLanguages.slice(0, 5).map((l) => (
                  <li key={l.language}>
                    {l.language}: {fmtBytes(l.bytes)} ({l.percentage}%)
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div>
            <h3 className="text-foreground font-semibold">Caveats</h3>
            <p className="text-foreground mt-2 leading-relaxed">
              Estimates only; real savings vary by team. The defaults are intentionally conservative
              <Citation source="cortex-2024" />
              <Citation source="atlassian-dx-2025" />. The CVE numbers count what Dependabot reports, not what is
              actually exploitable in your stack.
            </p>
          </div>

          <div>
            <h3 className="text-foreground font-semibold">Raw data</h3>
            <p className="text-foreground mt-2 leading-relaxed">
              The accompanying{' '}
              <code className="bg-muted rounded px-1.5 py-0.5 font-mono text-xs">patchwave-report.zip</code> ships the
              full per-repo dataset as JSON. Open{' '}
              <code className="bg-muted rounded px-1.5 py-0.5 font-mono text-xs">data/aggregated.json</code> for the
              rolled-up metrics this page renders.
            </p>
          </div>
        </div>
      </details>

      <div className="border-border text-muted-foreground mt-12 border-t pt-5 text-xs">
        Generated by patchwave-analysis. PatchWave is a project from{' '}
        <a href="https://contextbridge.ai" className="text-primary underline underline-offset-4">
          contextbridge
        </a>
        .
      </div>
    </section>
  );
}
