name: Main Branch

on:
  push:
    branches: [main]

concurrency:
  group: main
  cancel-in-progress: false

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
